version: '2'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        image: api-gdrscholars-app
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_LOG_LEVEL=debug
            - APP_URL=localhost
            - DB_PORT=3306
            - DB_HOST=mysql
            - DB_DATABASE=gdrscholars
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - MAIL_HOST=smtp.mailtrap.io
            - MAIL_PORT=2525
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null

    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        image: api-gdrscholars-web
        volumes:
            - ./:/var/www
        ports:
            - 80:80
        links:
            - app

    mysql:
        image: mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=gdrscholars
        ports:
            - 3306:3306

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
